{% set name = "mordred" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1115f9f3a3dde290dd68d51a5070fce43a62aab96b980cffc9d72b74a59e1c5a

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - networkx
    - numpy
    - python >={{ python_min }}
    - rdkit
    - six
    - tqdm 4.*

test:
  imports:
    - mordred
    - mordred._base
    - mordred.descriptors
    - mordred.error
    - mordred.surface_area
    - mordred.tests
  requires:
    - nose
    - pyyaml
    - python {{ python_min }}

about:
  home: https://github.com/mordred-descriptor/mordred
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Molecular descriptor calculator
  dev_url: https://github.com/mordred-descriptor/mordred

extra:
  recipe-maintainers:
    - simonbray
